version: '3.8'

networks:
  proxy:
    external: false
  internal:
    external: false

services:
  # Nginx proxy para manejar las conexiones entrantes y reenviarlas a los servicios correspondientes
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    networks:
      - proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  # Servicio para manejar certificados SSL automáticamente con Let's Encrypt
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=info@zimple.top
    depends_on:
      - nginx-proxy
    networks:
      - proxy

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mirlo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mirlo
      MYSQL_DATABASE: mirlo
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  # phpMyAdmin para administrar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mirlo_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mirlo
      VIRTUAL_HOST: phpmyadmin.mirloconstrucciones.top
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: phpmyadmin.mirloconstrucciones.top
      LETSENCRYPT_EMAIL: info@zimple.top
    depends_on:
      - db
      - nginx-proxy
    networks:
      - internal
      - proxy

  # Aplicación web PHP
  web:
    build: ./web
    container_name: mirlo_web
    restart: always
    environment:
      VIRTUAL_HOST: mirloconstrucciones.top,www.mirloconstrucciones.top
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: mirloconstrucciones.top,www.mirloconstrucciones.top
      LETSENCRYPT_EMAIL: info@zimple.top
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - nginx-proxy
    networks:
      - internal
      - proxy

volumes:
  db_data:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  acme:
