name: Build and Push Mirlo Web Docker Image

# Ejecutar el workflow solo cuando hay push a main
on:
  push:
    branches: [ main ]

# Variables de entorno globales
env:
  DOCKER_IMAGE: zimpletecnologia/mirlo-web
  DOCKER_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEV  # Especifica el environment que creaste
    
    steps:
    # 1. Checkout del código
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 2. Configurar Docker Buildx (para builds avanzados)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # 3. Login a Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # 4. Extraer metadatos para tags y labels
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-
    
    # 5. Build y push de la imagen Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./web
        file: ./web/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    # 6. Verificar imagen creada
    - name: Image digest
      run: echo "Image pushed with digest ${{ steps.build.outputs.digest }}"
